#!/bin/sh -e

if [ $# -ne 2 ]; then
    echo "Usage: tag_exists NAME TAG"
    exit 1
fi

NAME="$1"
TAG="$2"

API=https://quay.io/api/v1
STATUS=$(curl -s "$API/repository/cybozu/$NAME/tag/$TAG/images" -o /dev/null -w '%{http_code}\n')

if [ "$STATUS" = "200" ]; then
    echo "ok"
    exit 0
fi

echo "ng"
