#!/bin/sh -e

if [ $# -ne 2 ]; then
    echo "Usage: tag_exists NAME TAG"
    exit 1
fi

NAME="$1"
TAG="$2"

API=https://quay.io/api/v1
RESPONSE=$(curl -sSfL "$API/repository/cybozu/$NAME/tag/?specificTag=$TAG&onlyActiveTags=true")
NUM=$(echo "$RESPONSE" | jq '.tags | length')

if [ $NUM -gt 0 ]; then
    echo "ok"
    exit 0
fi

echo "ng"
