name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build images
    strategy:
      matrix:
        ubuntu-version: ["18.04", "20.04"]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ matrix.ubuntu-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        if: github.event_name != 'pull_request'
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io
      - name: Build and push ubuntu-minimal image if needed
        if: github.event_name != 'pull_request'
        run: |
          TAG_MINIMAL=$(cat TAG_MINIMAL)
          c="$(../tag_exists ubuntu-minimal $TAG_MINIMAL)"
          if [ "$c" = ng ]; then
              echo
              echo "building ubuntu-minimal ..."
              docker buildx build \
                --platform linux/amd64,linux/arm64/v8 \
                --push \
                -t quay.io/cybozu/ubuntu-minimal:$TAG_MINIMAL \
                --build-arg TAG_MINIMAL=$TAG_MINIMAL \
                ubuntu-minimal
          fi
      - name: Extract targets
        run: |
          TAG=$(cat TAG)
          for image in ubuntu ubuntu-dev ubuntu-debug; do
              c="$(../tag_exists $image $TAG)"
              if [ "$c" = ng ]; then
                  echo "build $image:$TAG"
                  echo $image >> BUILDS
              fi
          done
      - name: Build and push images
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -f BUILDS ]; then
              echo "nothing to build."
              exit 0
          fi
          TAG_MINIMAL=$(cat TAG_MINIMAL)
          TAG=$(cat TAG)
          BRANCH=$(cat BRANCH)
          for d in $(cat BUILDS); do
              echo
              echo "building $d ..."
              docker buildx build \
                --platform linux/amd64,linux/arm64/v8 \
                --push \
                -t quay.io/cybozu/${d}:$TAG \
                -t quay.io/cybozu/${d}:$BRANCH \
                --build-arg TAG_MINIMAL=$TAG_MINIMAL \
                --build-arg TAG=$TAG \
                ${d}
          done
