name: Pinact
on:
  pull_request:
    paths:
      - '.github/**/*.yaml'
      - '.github/**/*.yml'
jobs:
  verify-pinact:
    name: Verify pinned GitHub Actions comments
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.3
      - name: Verify SHAs and tag comments are consistent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pinact run --check --verify-comment
