name: verify
on:
  schedule:
    - cron: '0 0 * * 1-5' # At 00:00 on every day-of-week from Monday through Friday (UTC) (crontab.guru)

jobs:
  scan:
    name: Scan an Docker image by Trivy
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [18.04, 20.04, 22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        run: echo "tag=$(git show origin/main:${{ matrix.version }}/TAG)" >> $GITHUB_OUTPUT
        id: get-tag
      - name: Run Trivy (quay.io/cybozu/ubuntu:${{ env.tag }})
        uses: aquasecurity/trivy-action@0.10.0
        with:
          image-ref: ghcr.io/cybozu/ubuntu:${{ env.tag }}
          format: json
          output: ${{ env.tag }}.json
        env:
          tag: ${{ steps.get-tag.outputs.tag }}
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}
          path: ${{ steps.get-tag.outputs.tag }}.json

  build:
    needs: scan
    name: Verify images by Trivy
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Generate ID
        id: genid
        run: echo "id=$(date +'%Y%m%d')-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: trivy

      - name: Mkdir
        run: mkdir -p trivy-result page trivy-result/${{ steps.genid.outputs.id }}

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-18.04
          path: trivy-result/${{ steps.genid.outputs.id }}

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-20.04
          path: trivy-result/${{ steps.genid.outputs.id }}

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-22.04
          path: trivy-result/${{ steps.genid.outputs.id }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build daily-usn
        run: cd daily-usn && go build -v ./...

      - name: Generate HTML
        run: |
          new_result=trivy-result/$(ls -r trivy-result | sed -n '1 p')
          old_result=trivy-result/$(ls -r trivy-result | sed -n '2 p')
          daily-usn/daily-usn ${{ steps.genid.outputs.id }} $old_result $new_result | tee page/${{ steps.genid.outputs.id }}.html

      - name: Generate index.html
        run: echo "<a href=\"$HTML_FILE_NAME\">$HTML_FILE_NAME</a><br />" >> page/index.html
        env:
          HTML_FILE_NAME: "${{ steps.genid.outputs.id }}.html"

      - name: Upload generated HTML as an artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: page

      - name: Push results
        run: |
          git remote set-url origin https://github-actions:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}
          git config --local user.email "neco@cybozu.com"
          git config --local user.name "cybozu-neco"
          git add .
          git commit -m "[bot] Daily update (${{ steps.genid.outputs.id }})"
          git push origin trivy

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
